name: ogd-job
on:
  # push:
  #   paths-ignore:
  #     - '**.md'
  #     - 'docs/**.md'
  workflow_dispatch:
    inputs:
      version:
        description: 'identifier?'
        required: true

jobs:  
  build:
    runs-on: ubuntu-latest

    container:
      image: sogis/gretl:2.2.379

    steps:
      - uses: actions/checkout@v3

      - name: Run GRETL job
        #id: gretljob
        run: |
          gradle -b ${{ github.event.inputs.version }}/build.gradle
